name: Draft Basic ADR
description: Sample description
title: "[ADR]: "
labels:
- adr
- adr:draft
body:
- type: markdown
  attributes:
    value: |
      Welcome 👋 if this is your first time writing an ADR, please take the time
      to read this, otherwise jump right in.

      An Architectural Decision (AD) is a software design choice that addresses a
      functional or non-functional requirement that is architecturally significant.
      Do not take the term “architecture” too seriously or interpret it too strongly,
      instead, consider AD as Any Decision.

      The focus is capturing decisions, so it should be as easy as possible to
      a) write down the decisions and b) to version the decisions.

      ---

      - Github Markdown: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
      - Github supports Mermaid diagrams: https://mermaid.js.org
- type: textarea
  id: context
  attributes:
    label: Context and Problem Statement
    description: |
      Describe the context and problem statement. E.g.

      Decisions are being made and some are captured while others are not.
      Additionally, the decisions are captured in too many places. What process
      should we use and where should we capture them?
- type: textarea
  id: options
  attributes:
    label: Considered Options
    description: |
      List all considered options. E.g.

      * Confluence, use the DACI template
      * Google Docs, develop a template
      * Hashicorp Hermes, use the existing templates
      * Github, use the MADR template
    placeholder: |
      *
      *
      *
- type: textarea
  id: outcome
  attributes:
    label: Outcomes
    description: |
        Select the option that you chose to use and include an optional description. E.g.

        Chosen option: "Github" because it keeps our decisions close to the code
        while the MADR template focuses on making it easy to capture decisions
        and version them.
    placeholder: |
      Chosen option: